### ISSUE TITLE
Hi, this protect still work?

### ISSUE THREAD

**Issue by xtruong712** [cyberinferno/PacketDumper#1]
i try use this with game Vindictus but not efffect

**Comment by cyberinferno** [comment]
Check whether Vindictus uses Windows Socket 2 DLLs. Also did you update the path where packets have to be dumped? Usually packet log path is the issue.

**Comment by xtruong712** [comment]
How to check it, i use dll release. Can you help me? I just want get packet name client send to seẻver.

**Comment by xtruong712** [comment]
@cyberinferno  please help me 🥹 i can pay if can get packet name from client. Because i want update server file need find packet name

https://forum.ragezone.com/threads/get-packet-name-send-to-server.1236500/#post-9305411


I was post it to RZ but dont have come

**Comment by xtruong712** [comment]
![image](https://github.com/user-attachments/assets/af840a23-cd3c-450a-8490-e828f12e205f)
this is DLL it read

**Comment by cyberinferno** [comment]
This seems like HTTP protocol rather than TCP protocol. Hence my DLL might not help you.

**Comment by xtruong712** [comment]
oh you have any soft like that for http protocol?

**Comment by cyberinferno** [comment]
You can try to use tools like Wireshark. But it might not be helpful as data might be encrypted due to HTTPS.

**Comment by xtruong712** [comment]
yea thank you for replly
